### ISSUE TITLE
All values lost with newest version of struct (2020-05-12)

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [cosmocode/dokuwiki-plugin-structstatus#10]
Hi,

after updating to the newest version 2020-05-12 of the struct plugin all status values are lost. 

Regards
Juergen

**Comment by splitbrain** [comment]
@annda this plugin defines a type inheriting from Lookup. It probably needs the same adjustments we did to the lookup type, to properly store and retrieve the `rid`?

**Comment by annda** [comment]
I'll take a look at that soon.

**Comment by annda** [comment]
This is still work in progress https://github.com/cosmocode/dokuwiki-plugin-structstatus/pull/11

With a minor change in the first commit all the migrated status data should be displayed and editable again. The widget is still broken.

**Comment by annda** [comment]
Merged PR #11 fixes the incompatibility. Please reinstall the plugin.

**Comment by Juergen-aus-Zuendorf** [comment]
Thank you. 
The functionality is back again for newly entered data, but the old data is still lost. Is there any possibility to restore these old values?

**Comment by annda** [comment]
@Juergen-aus-Koeln  There should be no difference between old and new data at this point. Can you please export and post some sample old data that does not appear as expected? And some new data that works, for comparison.

**Comment by Juergen-aus-Zuendorf** [comment]
I'd like to, but how can I do that? I've exported the sql database of the struct plugin:
[struct.zip](https://github.com/cosmocode/dokuwiki-plugin-structstatus/files/4693768/struct.zip)
One of the relevant schemas is called "fbg_structstatus".

I don't know if this is what you need. If not, where can I find the relevant files for you to post?

**Comment by annda** [comment]
I see from the data you posted that it's a bit complicated. Struct plugins like structstatus at the moment have no data migration mechanisms of their own, but we are working on it and should have a solution soon to make the old data accessible again.

**Comment by Juergen-aus-Zuendorf** [comment]
Is there any news about this?

**Comment by dx9s** [comment]
I have a boss that wants me to recover from older backups lost data, and get the information back to a usable state that depends on struct and structstatus features of dokuwiki.

I looked briefly at pull request 11 and still don't see any data migration path. If somebody could write up a way to manually do this?

Things I would need is:
1) the table structure for the effected table(s) before and after the 2020-05-12 changes.
2) (for sanity checking) the plugin changes to verify currently installed structstatus version, the bits that are related. Is this everything in pull request 11 or is there more?

--Doug

**Comment by dx9s** [comment]
I think I found a workaround for updating the database in my case. data_policydetails has a column (col1) that references data_revisionstatus.  the col1 happens to be text with just a number in it, afterwards it was text with a json string in it. I just did an update:
update data_policies set col1 = '["",' || col1  || ']' 
to convert the column into something the current production code is expecting. This is heavily database dependent (what tables you use within struct and structstatus)

--Doug

**Comment by annda** [comment]
This is exactly what the migration would do, except of course the relevant tables and columns would be dynamically identified.

**Comment by annda** [comment]
@Juergen-aus-Koeln There is a draft PR with a working migration. You might fix your old data if you can back up your database and try this code in #13 . **Be cautious**: it has been only minimally tested at this point!

**Comment by Juergen-aus-Zuendorf** [comment]
Thank you very much !!!

For me it seems to work perfectly. I've changed the action.php, opened a page with struct data (structstatus) and then re-changed the action.php to the oroginal one. I hope this was the right way.

Best regards
Juergen
