### ISSUE TITLE
Copy of structured data

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [cosmocode/dokuwiki-plugin-structstatus#12]
Hi,

it would be great if the copypage-plugin would additionally copy data entered by the struct plugin, but here seems to be no simple way to implement copying data of the struct plugin when creating a new page.
See also https://github.com/orangain/dokuwiki-copypage-plugin/issues/14

Best regards
Juergen

**Comment by fschrempf** [comment]
@Juergen-aus-Zuendorf You are in the wrong repository. This is for the structstatus plugin, not the struct plugin.

**Comment by Juergen-aus-Zuendorf** [comment]
Oh, sorry!
I don't know what happened here. I've created a new issue in the right place now.
